BENCHNAME=rawcaudio
BENCHNAME2=rawdaudio

FILE1 = adpcm.c rawcaudio.c
FILE2 = adpcm.c rawdaudio.c

TARGETS=rawcaudio rawdaudio

SBTOPT?=-optimize -oneregion

STACKSIZE=400000

include ../../Makefile.common


